//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.LeagueDBServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersionInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ResultInfoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.SessionInfoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.SessionDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ScheduleInfoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ScheduleDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.RaceSessionDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ResultDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.IncidentReviewInfoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.CommentInfoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.CommentDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.SeasonInfoDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.SeasonDataDTO))]
    public partial class VersionInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModifiedOn {
            get {
                return this.LastModifiedOnField;
            }
            set {
                if ((this.LastModifiedOnField.Equals(value) != true)) {
                    this.LastModifiedOnField = value;
                    this.RaisePropertyChanged("LastModifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Results")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ResultDataDTO))]
    public partial class ResultInfoDTO : TestConsole.LeagueDBServiceRef.VersionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.SessionInfoDTO SessionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultId {
            get {
                return this.ResultIdField;
            }
            set {
                if ((this.ResultIdField.Equals(value) != true)) {
                    this.ResultIdField = value;
                    this.RaisePropertyChanged("ResultId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.SessionInfoDTO Session {
            get {
                return this.SessionField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionField, value) != true)) {
                    this.SessionField = value;
                    this.RaisePropertyChanged("Session");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Sessions")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.SessionDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.RaceSessionDataDTO))]
    public partial class SessionInfoDTO : TestConsole.LeagueDBServiceRef.VersionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iRLeagueManager.Enums.SessionType SessionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iRLeagueManager.Enums.SessionType SessionType {
            get {
                return this.SessionTypeField;
            }
            set {
                if ((this.SessionTypeField.Equals(value) != true)) {
                    this.SessionTypeField = value;
                    this.RaisePropertyChanged("SessionType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Sessions")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.RaceSessionDataDTO))]
    public partial class SessionDataDTO : TestConsole.LeagueDBServiceRef.SessionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.ScheduleInfoDTO ScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.ResultInfoDTO SessionResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByField, value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIdField, value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.ScheduleInfoDTO Schedule {
            get {
                return this.ScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleField, value) != true)) {
                    this.ScheduleField = value;
                    this.RaisePropertyChanged("Schedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.ResultInfoDTO SessionResult {
            get {
                return this.SessionResultField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionResultField, value) != true)) {
                    this.SessionResultField = value;
                    this.RaisePropertyChanged("SessionResult");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeagueMemberInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Members")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO))]
    public partial class LeagueMemberInfoDTO : TestConsole.LeagueDBServiceRef.VersionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((this.MemberIdField.Equals(value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeagueMemberDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Members")]
    [System.SerializableAttribute()]
    public partial class LeagueMemberDataDTO : TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DanLisaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IRacingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DanLisaId {
            get {
                return this.DanLisaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DanLisaIdField, value) != true)) {
                    this.DanLisaIdField = value;
                    this.RaisePropertyChanged("DanLisaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscordId {
            get {
                return this.DiscordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscordIdField, value) != true)) {
                    this.DiscordIdField = value;
                    this.RaisePropertyChanged("DiscordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IRacingId {
            get {
                return this.IRacingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IRacingIdField, value) != true)) {
                    this.IRacingIdField = value;
                    this.RaisePropertyChanged("IRacingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Sessions")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ScheduleDataDTO))]
    public partial class ScheduleInfoDTO : TestConsole.LeagueDBServiceRef.VersionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ScheduleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ScheduleId {
            get {
                return this.ScheduleIdField;
            }
            set {
                if ((this.ScheduleIdField.Equals(value) != true)) {
                    this.ScheduleIdField = value;
                    this.RaisePropertyChanged("ScheduleId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Sessions")]
    [System.SerializableAttribute()]
    public partial class ScheduleDataDTO : TestConsole.LeagueDBServiceRef.ScheduleInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.SessionDataDTO[] SessionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByField, value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.SessionDataDTO[] Sessions {
            get {
                return this.SessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionsField, value) != true)) {
                    this.SessionsField = value;
                    this.RaisePropertyChanged("Sessions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RaceSessionDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Sessions")]
    [System.SerializableAttribute()]
    public partial class RaceSessionDataDTO : TestConsole.LeagueDBServiceRef.SessionDataDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IrResultLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IrSessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PracticeAttachedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan PracticeLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool QualyAttachedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan QualyLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RaceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan RaceLengthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IrResultLink {
            get {
                return this.IrResultLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.IrResultLinkField, value) != true)) {
                    this.IrResultLinkField = value;
                    this.RaisePropertyChanged("IrResultLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IrSessionId {
            get {
                return this.IrSessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IrSessionIdField, value) != true)) {
                    this.IrSessionIdField = value;
                    this.RaisePropertyChanged("IrSessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Laps {
            get {
                return this.LapsField;
            }
            set {
                if ((this.LapsField.Equals(value) != true)) {
                    this.LapsField = value;
                    this.RaisePropertyChanged("Laps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PracticeAttached {
            get {
                return this.PracticeAttachedField;
            }
            set {
                if ((this.PracticeAttachedField.Equals(value) != true)) {
                    this.PracticeAttachedField = value;
                    this.RaisePropertyChanged("PracticeAttached");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan PracticeLength {
            get {
                return this.PracticeLengthField;
            }
            set {
                if ((this.PracticeLengthField.Equals(value) != true)) {
                    this.PracticeLengthField = value;
                    this.RaisePropertyChanged("PracticeLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool QualyAttached {
            get {
                return this.QualyAttachedField;
            }
            set {
                if ((this.QualyAttachedField.Equals(value) != true)) {
                    this.QualyAttachedField = value;
                    this.RaisePropertyChanged("QualyAttached");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan QualyLength {
            get {
                return this.QualyLengthField;
            }
            set {
                if ((this.QualyLengthField.Equals(value) != true)) {
                    this.QualyLengthField = value;
                    this.RaisePropertyChanged("QualyLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RaceId {
            get {
                return this.RaceIdField;
            }
            set {
                if ((this.RaceIdField.Equals(value) != true)) {
                    this.RaceIdField = value;
                    this.RaisePropertyChanged("RaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan RaceLength {
            get {
                return this.RaceLengthField;
            }
            set {
                if ((this.RaceLengthField.Equals(value) != true)) {
                    this.RaceLengthField = value;
                    this.RaisePropertyChanged("RaceLength");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Results")]
    [System.SerializableAttribute()]
    public partial class ResultDataDTO : TestConsole.LeagueDBServiceRef.ResultInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.ResultRowDataDTO[] RawResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.IncidentReviewInfoDTO[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.SeasonInfoDTO SeasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByField, value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.ResultRowDataDTO[] RawResults {
            get {
                return this.RawResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RawResultsField, value) != true)) {
                    this.RawResultsField = value;
                    this.RaisePropertyChanged("RawResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.IncidentReviewInfoDTO[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.SeasonInfoDTO Season {
            get {
                return this.SeasonField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonField, value) != true)) {
                    this.SeasonField = value;
                    this.RaisePropertyChanged("Season");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncidentReviewInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Reviews")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO))]
    public partial class IncidentReviewInfoDTO : TestConsole.LeagueDBServiceRef.VersionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReviewIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReviewId {
            get {
                return this.ReviewIdField;
            }
            set {
                if ((this.ReviewIdField.Equals(value) != true)) {
                    this.ReviewIdField = value;
                    this.RaisePropertyChanged("ReviewId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncidentReviewDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Reviews")]
    [System.SerializableAttribute()]
    public partial class IncidentReviewDataDTO : TestConsole.LeagueDBServiceRef.IncidentReviewInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO[] CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CornerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO[] InvolvedMembersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OnLapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.SessionInfoDTO SessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO[] Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Corner {
            get {
                return this.CornerField;
            }
            set {
                if ((this.CornerField.Equals(value) != true)) {
                    this.CornerField = value;
                    this.RaisePropertyChanged("Corner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO[] InvolvedMembers {
            get {
                return this.InvolvedMembersField;
            }
            set {
                if ((object.ReferenceEquals(this.InvolvedMembersField, value) != true)) {
                    this.InvolvedMembersField = value;
                    this.RaisePropertyChanged("InvolvedMembers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OnLap {
            get {
                return this.OnLapField;
            }
            set {
                if ((this.OnLapField.Equals(value) != true)) {
                    this.OnLapField = value;
                    this.RaisePropertyChanged("OnLap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.SessionInfoDTO Session {
            get {
                return this.SessionField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionField, value) != true)) {
                    this.SessionField = value;
                    this.RaisePropertyChanged("Session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Reviews")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.CommentDataDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO))]
    public partial class CommentInfoDTO : TestConsole.LeagueDBServiceRef.VersionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CommentIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CommentId {
            get {
                return this.CommentIdField;
            }
            set {
                if ((this.CommentIdField.Equals(value) != true)) {
                    this.CommentIdField = value;
                    this.RaisePropertyChanged("CommentId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Reviews")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO))]
    public partial class CommentDataDTO : TestConsole.LeagueDBServiceRef.CommentInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewCommentDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Reviews")]
    [System.SerializableAttribute()]
    public partial class ReviewCommentDataDTO : TestConsole.LeagueDBServiceRef.CommentDataDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO MemberAtFaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iRLeagueManager.Enums.VoteEnum VoteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO MemberAtFault {
            get {
                return this.MemberAtFaultField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberAtFaultField, value) != true)) {
                    this.MemberAtFaultField = value;
                    this.RaisePropertyChanged("MemberAtFault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iRLeagueManager.Enums.VoteEnum Vote {
            get {
                return this.VoteField;
            }
            set {
                if ((this.VoteField.Equals(value) != true)) {
                    this.VoteField = value;
                    this.RaisePropertyChanged("Vote");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestConsole.LeagueDBServiceRef.SeasonDataDTO))]
    public partial class SeasonInfoDTO : TestConsole.LeagueDBServiceRef.VersionInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeasonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeasonNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeasonId {
            get {
                return this.SeasonIdField;
            }
            set {
                if ((this.SeasonIdField.Equals(value) != true)) {
                    this.SeasonIdField = value;
                    this.RaisePropertyChanged("SeasonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeasonName {
            get {
                return this.SeasonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonNameField, value) != true)) {
                    this.SeasonNameField = value;
                    this.RaisePropertyChanged("SeasonName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer")]
    [System.SerializableAttribute()]
    public partial class SeasonDataDTO : TestConsole.LeagueDBServiceRef.SeasonInfoDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.ResultInfoDTO[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.IncidentReviewInfoDTO[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.ScheduleInfoDTO[] SchedulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SeasonEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SeasonStartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByField, value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.ResultInfoDTO[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.IncidentReviewInfoDTO[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.ScheduleInfoDTO[] Schedules {
            get {
                return this.SchedulesField;
            }
            set {
                if ((object.ReferenceEquals(this.SchedulesField, value) != true)) {
                    this.SchedulesField = value;
                    this.RaisePropertyChanged("Schedules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SeasonEnd {
            get {
                return this.SeasonEndField;
            }
            set {
                if ((this.SeasonEndField.Equals(value) != true)) {
                    this.SeasonEndField = value;
                    this.RaisePropertyChanged("SeasonEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SeasonStart {
            get {
                return this.SeasonStartField;
            }
            set {
                if ((this.SeasonStartField.Equals(value) != true)) {
                    this.SeasonStartField = value;
                    this.RaisePropertyChanged("SeasonStart");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultRowDataDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Results")]
    [System.SerializableAttribute()]
    public partial class ResultRowDataDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan AvgLapTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BonusPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompletedLapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FastLapNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan FastestLapTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinishPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IncidentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeadLapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO MemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan QualifyingTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RacePointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ResultRowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private iRLeagueManager.Enums.RaceStatusEnum StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan AvgLapTime {
            get {
                return this.AvgLapTimeField;
            }
            set {
                if ((this.AvgLapTimeField.Equals(value) != true)) {
                    this.AvgLapTimeField = value;
                    this.RaisePropertyChanged("AvgLapTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BonusPoints {
            get {
                return this.BonusPointsField;
            }
            set {
                if ((this.BonusPointsField.Equals(value) != true)) {
                    this.BonusPointsField = value;
                    this.RaisePropertyChanged("BonusPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarClass {
            get {
                return this.CarClassField;
            }
            set {
                if ((object.ReferenceEquals(this.CarClassField, value) != true)) {
                    this.CarClassField = value;
                    this.RaisePropertyChanged("CarClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarNumber {
            get {
                return this.CarNumberField;
            }
            set {
                if ((this.CarNumberField.Equals(value) != true)) {
                    this.CarNumberField = value;
                    this.RaisePropertyChanged("CarNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassId {
            get {
                return this.ClassIdField;
            }
            set {
                if ((this.ClassIdField.Equals(value) != true)) {
                    this.ClassIdField = value;
                    this.RaisePropertyChanged("ClassId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletedLaps {
            get {
                return this.CompletedLapsField;
            }
            set {
                if ((this.CompletedLapsField.Equals(value) != true)) {
                    this.CompletedLapsField = value;
                    this.RaisePropertyChanged("CompletedLaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FastLapNr {
            get {
                return this.FastLapNrField;
            }
            set {
                if ((this.FastLapNrField.Equals(value) != true)) {
                    this.FastLapNrField = value;
                    this.RaisePropertyChanged("FastLapNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan FastestLapTime {
            get {
                return this.FastestLapTimeField;
            }
            set {
                if ((this.FastestLapTimeField.Equals(value) != true)) {
                    this.FastestLapTimeField = value;
                    this.RaisePropertyChanged("FastestLapTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalPosition {
            get {
                return this.FinalPositionField;
            }
            set {
                if ((this.FinalPositionField.Equals(value) != true)) {
                    this.FinalPositionField = value;
                    this.RaisePropertyChanged("FinalPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinishPosition {
            get {
                return this.FinishPositionField;
            }
            set {
                if ((this.FinishPositionField.Equals(value) != true)) {
                    this.FinishPositionField = value;
                    this.RaisePropertyChanged("FinishPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Incidents {
            get {
                return this.IncidentsField;
            }
            set {
                if ((this.IncidentsField.Equals(value) != true)) {
                    this.IncidentsField = value;
                    this.RaisePropertyChanged("Incidents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeadLaps {
            get {
                return this.LeadLapsField;
            }
            set {
                if ((this.LeadLapsField.Equals(value) != true)) {
                    this.LeadLapsField = value;
                    this.RaisePropertyChanged("LeadLaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestConsole.LeagueDBServiceRef.LeagueMemberInfoDTO Member {
            get {
                return this.MemberField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberField, value) != true)) {
                    this.MemberField = value;
                    this.RaisePropertyChanged("Member");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionChange {
            get {
                return this.PositionChangeField;
            }
            set {
                if ((this.PositionChangeField.Equals(value) != true)) {
                    this.PositionChangeField = value;
                    this.RaisePropertyChanged("PositionChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan QualifyingTime {
            get {
                return this.QualifyingTimeField;
            }
            set {
                if ((this.QualifyingTimeField.Equals(value) != true)) {
                    this.QualifyingTimeField = value;
                    this.RaisePropertyChanged("QualifyingTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RacePoints {
            get {
                return this.RacePointsField;
            }
            set {
                if ((this.RacePointsField.Equals(value) != true)) {
                    this.RacePointsField = value;
                    this.RaisePropertyChanged("RacePoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ResultRowId {
            get {
                return this.ResultRowIdField;
            }
            set {
                if ((this.ResultRowIdField.Equals(value) != true)) {
                    this.ResultRowIdField = value;
                    this.RaisePropertyChanged("ResultRowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartPosition {
            get {
                return this.StartPositionField;
            }
            set {
                if ((this.StartPositionField.Equals(value) != true)) {
                    this.StartPositionField = value;
                    this.RaisePropertyChanged("StartPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iRLeagueManager.Enums.RaceStatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandingsRowDTO", Namespace="http://schemas.datacontract.org/2004/07/iRLeagueDatabase.DataTransfer.Results")]
    [System.SerializableAttribute()]
    public partial class StandingsRowDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FastestLapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PenaltyPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RacesCountedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RacesParticipatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Top10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Top15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Top20Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Top3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Top5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Change {
            get {
                return this.ChangeField;
            }
            set {
                if ((this.ChangeField.Equals(value) != true)) {
                    this.ChangeField = value;
                    this.RaisePropertyChanged("Change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FastestLaps {
            get {
                return this.FastestLapsField;
            }
            set {
                if ((this.FastestLapsField.Equals(value) != true)) {
                    this.FastestLapsField = value;
                    this.RaisePropertyChanged("FastestLaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberId {
            get {
                return this.MemberIdField;
            }
            set {
                if ((this.MemberIdField.Equals(value) != true)) {
                    this.MemberIdField = value;
                    this.RaisePropertyChanged("MemberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PenaltyPoints {
            get {
                return this.PenaltyPointsField;
            }
            set {
                if ((this.PenaltyPointsField.Equals(value) != true)) {
                    this.PenaltyPointsField = value;
                    this.RaisePropertyChanged("PenaltyPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsChange {
            get {
                return this.PointsChangeField;
            }
            set {
                if ((this.PointsChangeField.Equals(value) != true)) {
                    this.PointsChangeField = value;
                    this.RaisePropertyChanged("PointsChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Poles {
            get {
                return this.PolesField;
            }
            set {
                if ((this.PolesField.Equals(value) != true)) {
                    this.PolesField = value;
                    this.RaisePropertyChanged("Poles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos {
            get {
                return this.PosField;
            }
            set {
                if ((this.PosField.Equals(value) != true)) {
                    this.PosField = value;
                    this.RaisePropertyChanged("Pos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RacesCounted {
            get {
                return this.RacesCountedField;
            }
            set {
                if ((this.RacesCountedField.Equals(value) != true)) {
                    this.RacesCountedField = value;
                    this.RaisePropertyChanged("RacesCounted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RacesParticipated {
            get {
                return this.RacesParticipatedField;
            }
            set {
                if ((this.RacesParticipatedField.Equals(value) != true)) {
                    this.RacesParticipatedField = value;
                    this.RaisePropertyChanged("RacesParticipated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team {
            get {
                return this.TeamField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamField, value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top10 {
            get {
                return this.Top10Field;
            }
            set {
                if ((this.Top10Field.Equals(value) != true)) {
                    this.Top10Field = value;
                    this.RaisePropertyChanged("Top10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top15 {
            get {
                return this.Top15Field;
            }
            set {
                if ((this.Top15Field.Equals(value) != true)) {
                    this.Top15Field = value;
                    this.RaisePropertyChanged("Top15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top20 {
            get {
                return this.Top20Field;
            }
            set {
                if ((this.Top20Field.Equals(value) != true)) {
                    this.Top20Field = value;
                    this.RaisePropertyChanged("Top20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top3 {
            get {
                return this.Top3Field;
            }
            set {
                if ((this.Top3Field.Equals(value) != true)) {
                    this.Top3Field = value;
                    this.RaisePropertyChanged("Top3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top5 {
            get {
                return this.Top5Field;
            }
            set {
                if ((this.Top5Field.Equals(value) != true)) {
                    this.Top5Field = value;
                    this.RaisePropertyChanged("Top5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeagueDBServiceRef.ILeagueDBService")]
    public interface ILeagueDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/TestDB", ReplyAction="http://tempuri.org/ILeagueDBService/TestDBResponse")]
        string TestDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/TestDB", ReplyAction="http://tempuri.org/ILeagueDBService/TestDBResponse")]
        System.Threading.Tasks.Task<string> TestDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/Test", ReplyAction="http://tempuri.org/ILeagueDBService/TestResponse")]
        string Test(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/Test", ReplyAction="http://tempuri.org/ILeagueDBService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeason", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonResponse")]
        TestConsole.LeagueDBServiceRef.SeasonDataDTO GetSeason(int seasonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeason", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SeasonDataDTO> GetSeasonAsync(int seasonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasons", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonsResponse")]
        TestConsole.LeagueDBServiceRef.SeasonDataDTO[] GetSeasons(int[] seasonIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasons", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonsResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SeasonDataDTO[]> GetSeasonsAsync(int[] seasonIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSeason", ReplyAction="http://tempuri.org/ILeagueDBService/PutSeasonResponse")]
        TestConsole.LeagueDBServiceRef.SeasonDataDTO PutSeason(TestConsole.LeagueDBServiceRef.SeasonDataDTO season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSeason", ReplyAction="http://tempuri.org/ILeagueDBService/PutSeasonResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SeasonDataDTO> PutSeasonAsync(TestConsole.LeagueDBServiceRef.SeasonDataDTO season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetMemberResponse")]
        TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO GetMember(int memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetMemberResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO> GetMemberAsync(int memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMembers", ReplyAction="http://tempuri.org/ILeagueDBService/GetMembersResponse")]
        TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] GetMembers(int[] memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMembers", ReplyAction="http://tempuri.org/ILeagueDBService/GetMembersResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[]> GetMembersAsync(int[] memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/UpdateMemberList", ReplyAction="http://tempuri.org/ILeagueDBService/UpdateMemberListResponse")]
        TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] UpdateMemberList(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] members);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/UpdateMemberList", ReplyAction="http://tempuri.org/ILeagueDBService/UpdateMemberListResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[]> UpdateMemberListAsync(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] members);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetLastMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetLastMemberResponse")]
        TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO GetLastMember();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetLastMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetLastMemberResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO> GetLastMemberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutMember", ReplyAction="http://tempuri.org/ILeagueDBService/PutMemberResponse")]
        TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO PutMember(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutMember", ReplyAction="http://tempuri.org/ILeagueDBService/PutMemberResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO> PutMemberAsync(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetReview", ReplyAction="http://tempuri.org/ILeagueDBService/GetReviewResponse")]
        TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO GetReview(int reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetReview", ReplyAction="http://tempuri.org/ILeagueDBService/GetReviewResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO> GetReviewAsync(int reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutReview", ReplyAction="http://tempuri.org/ILeagueDBService/PutReviewResponse")]
        TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO PutReview(TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutReview", ReplyAction="http://tempuri.org/ILeagueDBService/PutReviewResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO> PutReviewAsync(TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSession", ReplyAction="http://tempuri.org/ILeagueDBService/GetSessionResponse")]
        TestConsole.LeagueDBServiceRef.SessionDataDTO GetSession(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSession", ReplyAction="http://tempuri.org/ILeagueDBService/GetSessionResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SessionDataDTO> GetSessionAsync(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSession", ReplyAction="http://tempuri.org/ILeagueDBService/PutSessionResponse")]
        TestConsole.LeagueDBServiceRef.SessionDataDTO PutSession(TestConsole.LeagueDBServiceRef.SessionDataDTO session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSession", ReplyAction="http://tempuri.org/ILeagueDBService/PutSessionResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SessionDataDTO> PutSessionAsync(TestConsole.LeagueDBServiceRef.SessionDataDTO session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetComment", ReplyAction="http://tempuri.org/ILeagueDBService/GetCommentResponse")]
        TestConsole.LeagueDBServiceRef.CommentDataDTO GetComment(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetComment", ReplyAction="http://tempuri.org/ILeagueDBService/GetCommentResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.CommentDataDTO> GetCommentAsync(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutComment", ReplyAction="http://tempuri.org/ILeagueDBService/PutCommentResponse")]
        TestConsole.LeagueDBServiceRef.CommentDataDTO PutComment(TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutComment", ReplyAction="http://tempuri.org/ILeagueDBService/PutCommentResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.CommentDataDTO> PutCommentAsync(TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/GetScheduleResponse")]
        TestConsole.LeagueDBServiceRef.ScheduleDataDTO GetSchedule(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/GetScheduleResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ScheduleDataDTO> GetScheduleAsync(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedules", ReplyAction="http://tempuri.org/ILeagueDBService/GetSchedulesResponse")]
        TestConsole.LeagueDBServiceRef.ScheduleDataDTO[] GetSchedules(int[] scheduleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedules", ReplyAction="http://tempuri.org/ILeagueDBService/GetSchedulesResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ScheduleDataDTO[]> GetSchedulesAsync(int[] scheduleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/PutScheduleResponse")]
        TestConsole.LeagueDBServiceRef.ScheduleDataDTO PutSchedule(TestConsole.LeagueDBServiceRef.ScheduleDataDTO schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/PutScheduleResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ScheduleDataDTO> PutScheduleAsync(TestConsole.LeagueDBServiceRef.ScheduleDataDTO schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetResult", ReplyAction="http://tempuri.org/ILeagueDBService/GetResultResponse")]
        TestConsole.LeagueDBServiceRef.ResultDataDTO GetResult(int resultId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetResult", ReplyAction="http://tempuri.org/ILeagueDBService/GetResultResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ResultDataDTO> GetResultAsync(int resultId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutResult", ReplyAction="http://tempuri.org/ILeagueDBService/PutResultResponse")]
        TestConsole.LeagueDBServiceRef.ResultDataDTO PutResult(TestConsole.LeagueDBServiceRef.ResultDataDTO result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutResult", ReplyAction="http://tempuri.org/ILeagueDBService/PutResultResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ResultDataDTO> PutResultAsync(TestConsole.LeagueDBServiceRef.ResultDataDTO result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasonStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonStandingsResponse")]
        TestConsole.LeagueDBServiceRef.StandingsRowDTO[] GetSeasonStandings(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasonStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonStandingsResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.StandingsRowDTO[]> GetSeasonStandingsAsync(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetTeamStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetTeamStandingsResponse")]
        TestConsole.LeagueDBServiceRef.StandingsRowDTO[] GetTeamStandings(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetTeamStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetTeamStandingsResponse")]
        System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.StandingsRowDTO[]> GetTeamStandingsAsync(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/CleanUpSessions", ReplyAction="http://tempuri.org/ILeagueDBService/CleanUpSessionsResponse")]
        void CleanUpSessions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/CleanUpSessions", ReplyAction="http://tempuri.org/ILeagueDBService/CleanUpSessionsResponse")]
        System.Threading.Tasks.Task CleanUpSessionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeagueDBServiceChannel : TestConsole.LeagueDBServiceRef.ILeagueDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeagueDBServiceClient : System.ServiceModel.ClientBase<TestConsole.LeagueDBServiceRef.ILeagueDBService>, TestConsole.LeagueDBServiceRef.ILeagueDBService {
        
        public LeagueDBServiceClient() {
        }
        
        public LeagueDBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeagueDBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeagueDBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeagueDBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestDB() {
            return base.Channel.TestDB();
        }
        
        public System.Threading.Tasks.Task<string> TestDBAsync() {
            return base.Channel.TestDBAsync();
        }
        
        public string Test(string name) {
            return base.Channel.Test(name);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string name) {
            return base.Channel.TestAsync(name);
        }
        
        public TestConsole.LeagueDBServiceRef.SeasonDataDTO GetSeason(int seasonId) {
            return base.Channel.GetSeason(seasonId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SeasonDataDTO> GetSeasonAsync(int seasonId) {
            return base.Channel.GetSeasonAsync(seasonId);
        }
        
        public TestConsole.LeagueDBServiceRef.SeasonDataDTO[] GetSeasons(int[] seasonIds) {
            return base.Channel.GetSeasons(seasonIds);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SeasonDataDTO[]> GetSeasonsAsync(int[] seasonIds) {
            return base.Channel.GetSeasonsAsync(seasonIds);
        }
        
        public TestConsole.LeagueDBServiceRef.SeasonDataDTO PutSeason(TestConsole.LeagueDBServiceRef.SeasonDataDTO season) {
            return base.Channel.PutSeason(season);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SeasonDataDTO> PutSeasonAsync(TestConsole.LeagueDBServiceRef.SeasonDataDTO season) {
            return base.Channel.PutSeasonAsync(season);
        }
        
        public TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO GetMember(int memberId) {
            return base.Channel.GetMember(memberId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO> GetMemberAsync(int memberId) {
            return base.Channel.GetMemberAsync(memberId);
        }
        
        public TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] GetMembers(int[] memberId) {
            return base.Channel.GetMembers(memberId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[]> GetMembersAsync(int[] memberId) {
            return base.Channel.GetMembersAsync(memberId);
        }
        
        public TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] UpdateMemberList(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] members) {
            return base.Channel.UpdateMemberList(members);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[]> UpdateMemberListAsync(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO[] members) {
            return base.Channel.UpdateMemberListAsync(members);
        }
        
        public TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO GetLastMember() {
            return base.Channel.GetLastMember();
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO> GetLastMemberAsync() {
            return base.Channel.GetLastMemberAsync();
        }
        
        public TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO PutMember(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO member) {
            return base.Channel.PutMember(member);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO> PutMemberAsync(TestConsole.LeagueDBServiceRef.LeagueMemberDataDTO member) {
            return base.Channel.PutMemberAsync(member);
        }
        
        public TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO GetReview(int reviewId) {
            return base.Channel.GetReview(reviewId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO> GetReviewAsync(int reviewId) {
            return base.Channel.GetReviewAsync(reviewId);
        }
        
        public TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO PutReview(TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO review) {
            return base.Channel.PutReview(review);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO> PutReviewAsync(TestConsole.LeagueDBServiceRef.IncidentReviewDataDTO review) {
            return base.Channel.PutReviewAsync(review);
        }
        
        public TestConsole.LeagueDBServiceRef.SessionDataDTO GetSession(int sessionId) {
            return base.Channel.GetSession(sessionId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SessionDataDTO> GetSessionAsync(int sessionId) {
            return base.Channel.GetSessionAsync(sessionId);
        }
        
        public TestConsole.LeagueDBServiceRef.SessionDataDTO PutSession(TestConsole.LeagueDBServiceRef.SessionDataDTO session) {
            return base.Channel.PutSession(session);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.SessionDataDTO> PutSessionAsync(TestConsole.LeagueDBServiceRef.SessionDataDTO session) {
            return base.Channel.PutSessionAsync(session);
        }
        
        public TestConsole.LeagueDBServiceRef.CommentDataDTO GetComment(int commentId) {
            return base.Channel.GetComment(commentId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.CommentDataDTO> GetCommentAsync(int commentId) {
            return base.Channel.GetCommentAsync(commentId);
        }
        
        public TestConsole.LeagueDBServiceRef.CommentDataDTO PutComment(TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO comment) {
            return base.Channel.PutComment(comment);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.CommentDataDTO> PutCommentAsync(TestConsole.LeagueDBServiceRef.ReviewCommentDataDTO comment) {
            return base.Channel.PutCommentAsync(comment);
        }
        
        public TestConsole.LeagueDBServiceRef.ScheduleDataDTO GetSchedule(int scheduleId) {
            return base.Channel.GetSchedule(scheduleId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ScheduleDataDTO> GetScheduleAsync(int scheduleId) {
            return base.Channel.GetScheduleAsync(scheduleId);
        }
        
        public TestConsole.LeagueDBServiceRef.ScheduleDataDTO[] GetSchedules(int[] scheduleIds) {
            return base.Channel.GetSchedules(scheduleIds);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ScheduleDataDTO[]> GetSchedulesAsync(int[] scheduleIds) {
            return base.Channel.GetSchedulesAsync(scheduleIds);
        }
        
        public TestConsole.LeagueDBServiceRef.ScheduleDataDTO PutSchedule(TestConsole.LeagueDBServiceRef.ScheduleDataDTO schedule) {
            return base.Channel.PutSchedule(schedule);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ScheduleDataDTO> PutScheduleAsync(TestConsole.LeagueDBServiceRef.ScheduleDataDTO schedule) {
            return base.Channel.PutScheduleAsync(schedule);
        }
        
        public TestConsole.LeagueDBServiceRef.ResultDataDTO GetResult(int resultId) {
            return base.Channel.GetResult(resultId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ResultDataDTO> GetResultAsync(int resultId) {
            return base.Channel.GetResultAsync(resultId);
        }
        
        public TestConsole.LeagueDBServiceRef.ResultDataDTO PutResult(TestConsole.LeagueDBServiceRef.ResultDataDTO result) {
            return base.Channel.PutResult(result);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.ResultDataDTO> PutResultAsync(TestConsole.LeagueDBServiceRef.ResultDataDTO result) {
            return base.Channel.PutResultAsync(result);
        }
        
        public TestConsole.LeagueDBServiceRef.StandingsRowDTO[] GetSeasonStandings(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetSeasonStandings(seasonId, lastSessionId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.StandingsRowDTO[]> GetSeasonStandingsAsync(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetSeasonStandingsAsync(seasonId, lastSessionId);
        }
        
        public TestConsole.LeagueDBServiceRef.StandingsRowDTO[] GetTeamStandings(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetTeamStandings(seasonId, lastSessionId);
        }
        
        public System.Threading.Tasks.Task<TestConsole.LeagueDBServiceRef.StandingsRowDTO[]> GetTeamStandingsAsync(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetTeamStandingsAsync(seasonId, lastSessionId);
        }
        
        public void CleanUpSessions() {
            base.Channel.CleanUpSessions();
        }
        
        public System.Threading.Tasks.Task CleanUpSessionsAsync() {
            return base.Channel.CleanUpSessionsAsync();
        }
    }
}
