//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.LeagueServiceDebug {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeagueServiceDebug.ILeagueDBService")]
    public interface ILeagueDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/TestDB", ReplyAction="http://tempuri.org/ILeagueDBService/TestDBResponse")]
        string TestDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/TestDB", ReplyAction="http://tempuri.org/ILeagueDBService/TestDBResponse")]
        System.Threading.Tasks.Task<string> TestDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/Test", ReplyAction="http://tempuri.org/ILeagueDBService/TestResponse")]
        string Test(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/Test", ReplyAction="http://tempuri.org/ILeagueDBService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeason", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO GetSeason(int seasonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeason", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO> GetSeasonAsync(int seasonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasons", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonsResponse")]
        iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO[] GetSeasons(int[] seasonIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasons", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonsResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO[]> GetSeasonsAsync(int[] seasonIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSeason", ReplyAction="http://tempuri.org/ILeagueDBService/PutSeasonResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO PutSeason(iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSeason", ReplyAction="http://tempuri.org/ILeagueDBService/PutSeasonResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO> PutSeasonAsync(iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO season);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetMemberResponse")]
        iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO GetMember(int memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetMemberResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO> GetMemberAsync(int memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMembers", ReplyAction="http://tempuri.org/ILeagueDBService/GetMembersResponse")]
        iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] GetMembers(int[] memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetMembers", ReplyAction="http://tempuri.org/ILeagueDBService/GetMembersResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[]> GetMembersAsync(int[] memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/UpdateMemberList", ReplyAction="http://tempuri.org/ILeagueDBService/UpdateMemberListResponse")]
        iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] UpdateMemberList(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] members);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/UpdateMemberList", ReplyAction="http://tempuri.org/ILeagueDBService/UpdateMemberListResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[]> UpdateMemberListAsync(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] members);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetLastMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetLastMemberResponse")]
        iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO GetLastMember();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetLastMember", ReplyAction="http://tempuri.org/ILeagueDBService/GetLastMemberResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO> GetLastMemberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutMember", ReplyAction="http://tempuri.org/ILeagueDBService/PutMemberResponse")]
        iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO PutMember(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutMember", ReplyAction="http://tempuri.org/ILeagueDBService/PutMemberResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO> PutMemberAsync(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetReview", ReplyAction="http://tempuri.org/ILeagueDBService/GetReviewResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.SessionDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.RaceSessionDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO GetReview(int reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetReview", ReplyAction="http://tempuri.org/ILeagueDBService/GetReviewResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO> GetReviewAsync(int reviewId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutReview", ReplyAction="http://tempuri.org/ILeagueDBService/PutReviewResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.SessionDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.RaceSessionDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO PutReview(iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutReview", ReplyAction="http://tempuri.org/ILeagueDBService/PutReviewResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO> PutReviewAsync(iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSession", ReplyAction="http://tempuri.org/ILeagueDBService/GetSessionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.RaceSessionDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.ResultDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.SessionDataDTO GetSession(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSession", ReplyAction="http://tempuri.org/ILeagueDBService/GetSessionResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SessionDataDTO> GetSessionAsync(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSession", ReplyAction="http://tempuri.org/ILeagueDBService/PutSessionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.RaceSessionDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.ResultDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.SessionDataDTO PutSession(iRLeagueManager.LeagueDBServiceRef.SessionDataDTO session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSession", ReplyAction="http://tempuri.org/ILeagueDBService/PutSessionResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SessionDataDTO> PutSessionAsync(iRLeagueManager.LeagueDBServiceRef.SessionDataDTO session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetComment", ReplyAction="http://tempuri.org/ILeagueDBService/GetCommentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.ReviewCommentDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.CommentDataDTO GetComment(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetComment", ReplyAction="http://tempuri.org/ILeagueDBService/GetCommentResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.CommentDataDTO> GetCommentAsync(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutComment", ReplyAction="http://tempuri.org/ILeagueDBService/PutCommentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.ReviewCommentDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.CommentDataDTO PutComment(iRLeagueManager.LeagueDBServiceRef.ReviewCommentDataDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutComment", ReplyAction="http://tempuri.org/ILeagueDBService/PutCommentResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.CommentDataDTO> PutCommentAsync(iRLeagueManager.LeagueDBServiceRef.ReviewCommentDataDTO comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/GetScheduleResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO GetSchedule(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/GetScheduleResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO> GetScheduleAsync(int scheduleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedules", ReplyAction="http://tempuri.org/ILeagueDBService/GetSchedulesResponse")]
        iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO[] GetSchedules(int[] scheduleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSchedules", ReplyAction="http://tempuri.org/ILeagueDBService/GetSchedulesResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO[]> GetSchedulesAsync(int[] scheduleIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/PutScheduleResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO PutSchedule(iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutSchedule", ReplyAction="http://tempuri.org/ILeagueDBService/PutScheduleResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO> PutScheduleAsync(iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO schedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetResult", ReplyAction="http://tempuri.org/ILeagueDBService/GetResultResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.ResultDataDTO GetResult(int resultId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetResult", ReplyAction="http://tempuri.org/ILeagueDBService/GetResultResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ResultDataDTO> GetResultAsync(int resultId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutResult", ReplyAction="http://tempuri.org/ILeagueDBService/PutResultResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO))]
        iRLeagueManager.LeagueDBServiceRef.ResultDataDTO PutResult(iRLeagueManager.LeagueDBServiceRef.ResultDataDTO result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/PutResult", ReplyAction="http://tempuri.org/ILeagueDBService/PutResultResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ResultDataDTO> PutResultAsync(iRLeagueManager.LeagueDBServiceRef.ResultDataDTO result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasonStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonStandingsResponse")]
        iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[] GetSeasonStandings(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetSeasonStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetSeasonStandingsResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[]> GetSeasonStandingsAsync(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetTeamStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetTeamStandingsResponse")]
        iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[] GetTeamStandings(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/GetTeamStandings", ReplyAction="http://tempuri.org/ILeagueDBService/GetTeamStandingsResponse")]
        System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[]> GetTeamStandingsAsync(int seasonId, System.Nullable<int> lastSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/CleanUpSessions", ReplyAction="http://tempuri.org/ILeagueDBService/CleanUpSessionsResponse")]
        void CleanUpSessions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeagueDBService/CleanUpSessions", ReplyAction="http://tempuri.org/ILeagueDBService/CleanUpSessionsResponse")]
        System.Threading.Tasks.Task CleanUpSessionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeagueDBServiceChannel : TestConsole.LeagueServiceDebug.ILeagueDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeagueDBServiceClient : System.ServiceModel.ClientBase<TestConsole.LeagueServiceDebug.ILeagueDBService>, TestConsole.LeagueServiceDebug.ILeagueDBService {
        
        public LeagueDBServiceClient() {
        }
        
        public LeagueDBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeagueDBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeagueDBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeagueDBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestDB() {
            return base.Channel.TestDB();
        }
        
        public System.Threading.Tasks.Task<string> TestDBAsync() {
            return base.Channel.TestDBAsync();
        }
        
        public string Test(string name) {
            return base.Channel.Test(name);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string name) {
            return base.Channel.TestAsync(name);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO GetSeason(int seasonId) {
            return base.Channel.GetSeason(seasonId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO> GetSeasonAsync(int seasonId) {
            return base.Channel.GetSeasonAsync(seasonId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO[] GetSeasons(int[] seasonIds) {
            return base.Channel.GetSeasons(seasonIds);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO[]> GetSeasonsAsync(int[] seasonIds) {
            return base.Channel.GetSeasonsAsync(seasonIds);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO PutSeason(iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO season) {
            return base.Channel.PutSeason(season);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO> PutSeasonAsync(iRLeagueManager.LeagueDBServiceRef.SeasonDataDTO season) {
            return base.Channel.PutSeasonAsync(season);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO GetMember(int memberId) {
            return base.Channel.GetMember(memberId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO> GetMemberAsync(int memberId) {
            return base.Channel.GetMemberAsync(memberId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] GetMembers(int[] memberId) {
            return base.Channel.GetMembers(memberId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[]> GetMembersAsync(int[] memberId) {
            return base.Channel.GetMembersAsync(memberId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] UpdateMemberList(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] members) {
            return base.Channel.UpdateMemberList(members);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[]> UpdateMemberListAsync(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO[] members) {
            return base.Channel.UpdateMemberListAsync(members);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO GetLastMember() {
            return base.Channel.GetLastMember();
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO> GetLastMemberAsync() {
            return base.Channel.GetLastMemberAsync();
        }
        
        public iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO PutMember(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO member) {
            return base.Channel.PutMember(member);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO> PutMemberAsync(iRLeagueManager.LeagueDBServiceRef.LeagueMemberDataDTO member) {
            return base.Channel.PutMemberAsync(member);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO GetReview(int reviewId) {
            return base.Channel.GetReview(reviewId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO> GetReviewAsync(int reviewId) {
            return base.Channel.GetReviewAsync(reviewId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO PutReview(iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO review) {
            return base.Channel.PutReview(review);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO> PutReviewAsync(iRLeagueManager.LeagueDBServiceRef.IncidentReviewDataDTO review) {
            return base.Channel.PutReviewAsync(review);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.SessionDataDTO GetSession(int sessionId) {
            return base.Channel.GetSession(sessionId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SessionDataDTO> GetSessionAsync(int sessionId) {
            return base.Channel.GetSessionAsync(sessionId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.SessionDataDTO PutSession(iRLeagueManager.LeagueDBServiceRef.SessionDataDTO session) {
            return base.Channel.PutSession(session);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.SessionDataDTO> PutSessionAsync(iRLeagueManager.LeagueDBServiceRef.SessionDataDTO session) {
            return base.Channel.PutSessionAsync(session);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.CommentDataDTO GetComment(int commentId) {
            return base.Channel.GetComment(commentId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.CommentDataDTO> GetCommentAsync(int commentId) {
            return base.Channel.GetCommentAsync(commentId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.CommentDataDTO PutComment(iRLeagueManager.LeagueDBServiceRef.ReviewCommentDataDTO comment) {
            return base.Channel.PutComment(comment);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.CommentDataDTO> PutCommentAsync(iRLeagueManager.LeagueDBServiceRef.ReviewCommentDataDTO comment) {
            return base.Channel.PutCommentAsync(comment);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO GetSchedule(int scheduleId) {
            return base.Channel.GetSchedule(scheduleId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO> GetScheduleAsync(int scheduleId) {
            return base.Channel.GetScheduleAsync(scheduleId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO[] GetSchedules(int[] scheduleIds) {
            return base.Channel.GetSchedules(scheduleIds);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO[]> GetSchedulesAsync(int[] scheduleIds) {
            return base.Channel.GetSchedulesAsync(scheduleIds);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO PutSchedule(iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO schedule) {
            return base.Channel.PutSchedule(schedule);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO> PutScheduleAsync(iRLeagueManager.LeagueDBServiceRef.ScheduleDataDTO schedule) {
            return base.Channel.PutScheduleAsync(schedule);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.ResultDataDTO GetResult(int resultId) {
            return base.Channel.GetResult(resultId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ResultDataDTO> GetResultAsync(int resultId) {
            return base.Channel.GetResultAsync(resultId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.ResultDataDTO PutResult(iRLeagueManager.LeagueDBServiceRef.ResultDataDTO result) {
            return base.Channel.PutResult(result);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.ResultDataDTO> PutResultAsync(iRLeagueManager.LeagueDBServiceRef.ResultDataDTO result) {
            return base.Channel.PutResultAsync(result);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[] GetSeasonStandings(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetSeasonStandings(seasonId, lastSessionId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[]> GetSeasonStandingsAsync(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetSeasonStandingsAsync(seasonId, lastSessionId);
        }
        
        public iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[] GetTeamStandings(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetTeamStandings(seasonId, lastSessionId);
        }
        
        public System.Threading.Tasks.Task<iRLeagueManager.LeagueDBServiceRef.StandingsRowDTO[]> GetTeamStandingsAsync(int seasonId, System.Nullable<int> lastSessionId) {
            return base.Channel.GetTeamStandingsAsync(seasonId, lastSessionId);
        }
        
        public void CleanUpSessions() {
            base.Channel.CleanUpSessions();
        }
        
        public System.Threading.Tasks.Task CleanUpSessionsAsync() {
            return base.Channel.CleanUpSessionsAsync();
        }
    }
}
